// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/VladPetriv/tg_scanner/internal/model"

// ReplieRepo is an autogenerated mock type for the ReplieRepo type
type ReplieRepo struct {
	mock.Mock
}

// CreateReplie provides a mock function with given fields: replie
func (_m *ReplieRepo) CreateReplie(replie *model.Replie) (int, error) {
	ret := _m.Called(replie)

	var r0 int
	if rf, ok := ret.Get(0).(func(*model.Replie) int); ok {
		r0 = rf(replie)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Replie) error); ok {
		r1 = rf(replie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplie provides a mock function with given fields: replieID
func (_m *ReplieRepo) GetReplie(replieID int) (*model.Replie, error) {
	ret := _m.Called(replieID)

	var r0 *model.Replie
	if rf, ok := ret.Get(0).(func(int) *model.Replie); ok {
		r0 = rf(replieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Replie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(replieID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReplieByName provides a mock function with given fields: name
func (_m *ReplieRepo) GetReplieByName(name string) (*model.Replie, error) {
	ret := _m.Called(name)

	var r0 *model.Replie
	if rf, ok := ret.Get(0).(func(string) *model.Replie); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Replie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
