// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/VladPetriv/tg_scanner/internal/model"

// ChannelService is an autogenerated mock type for the ChannelService type
type ChannelService struct {
	mock.Mock
}

// CreateChannel provides a mock function with given fields: channel
func (_m *ChannelService) CreateChannel(channel *model.Channel) error {
	ret := _m.Called(channel)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Channel) error); ok {
		r0 = rf(channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChannelByName provides a mock function with given fields: name
func (_m *ChannelService) GetChannelByName(name string) (*model.Channel, error) {
	ret := _m.Called(name)

	var r0 *model.Channel
	if rf, ok := ret.Get(0).(func(string) *model.Channel); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
