name: ci

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  go-tests:
    name: Unit  tests
    rusn-on: ubunut-latest
    steps:
      - uses: actions/setup-go@v3
        with: {go-version: 1.18}

      - uses: actions/checkout@v3

      - name: Go modules Cache 
        uses: actions/cache@v2
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Run Unit tests
        run: go test -v ./...
